### ISSUE TITLE
Atualizar Roadmap de DevOps

### ISSUE THREAD

**Issue by Yoshida-Eduardo** [fga-eps-mds/2019.1-Grupo-1#220]
**Tarefas**

- [x] Atualizar documentação referente ao Roadmap de devops

**Critérios de aceitação**

- [x] Documentação deve estar atualizada
- [x] Documentação deve estar disponível no GH Pages
