### ISSUE TITLE
Elaborar o roadmap do projeto 

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#29]
Criar documento roadmap de forma que esteja de acordo com backlog do produto.
 * Tasks
  - [x] Criar documento com base nos tópicos: epicos, features e issues
  - [x] Validar documento
  - [x] Documentar no github pages

 * Critérios de aceitação
  - [x] Linkar página na issue
  - [x] Estar validado e documentado no github pages

**Comment by KahCosta** [comment]
Roadmap inicial elaborado! porém necessita do feedback para saber se está seguinda a estrutura correta
