### ISSUE TITLE
Elaborar o roadmap de papeis

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#37]
Elaborar documento: RoadMap para cada um dos papéis existentes: 
 * Tarefas
- [x] RoadMap PO
- [x] RoadMap Scrum Master
- [x] RoadMap Arquitetura
- [x] RoadMap Devops

 * Critérios de aceitação
- [x] Documento devidamente adicionado no Github Pages 
- [x] Link do documento disponível na issue

**Comment by KahCosta** [comment]
Criei um template no drive para adição de roadmap de papeis a fim de facilitar a criação do mesmo!
Link [Aqui](https://docs.google.com/drawings/d/1HZG9VY-bHsnpbslSyqKlovRo4LdcPz-SpqnkaK7eRZE/edit?usp=drive_web&ouid=109200074847843814608)

**Comment by Lucas362** [comment]
Com base no template disponibilizado pela @KahCosta, foi desenvolvido o seguinte [roadmap para o papel de Scrum Master](https://docs.google.com/drawings/d/1-o5VtlV271EBGAv3PWQKGm9Rh_IV9neK-X1Lm-5ZOsg/edit?usp=sharing)

**Comment by GuiMarques98** [comment]
Com base no template disponibilizado pela @KahCosta, foi desenvolvido o RoadMap do Arquiteto.
