### ISSUE TITLE
Conteúdo

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#52]
Breve comentário sobre o contexto e descrição da issue.

**Tarefas**

- [ ] Passo a ser feito para que algum critério de aceitação seja cumprido

**Critérios de aceitação**

- [ ] Cada critério de aceitação descreve uma condição necessária para que a issue seja considerada completa
- [ ] A condição necessária pode ser a nível de comportamento ou resultado
