### ISSUE TITLE
Refatorar RoadMap 

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#95]
Refatorar RoadMap de acordo com novas decisões tomadas quanto ao que será entregue na R1

**Tarefas**
  - [x] Refatorar documento
  - [x] Validar documento
  - [x] Documentar no github pages

 * Critérios de aceitação
  - [x] Linkar página na issue
  - [x] Estar validado e documentado no github pages

**Comment by KahCosta** [comment]
Tirar aspecto de tasks do RoadMap

**Comment by KahCosta** [comment]
Os monitores levantaram alguns questionamentos sobre a construção do RoadMap:
- Tirar Aspectos de tasks 
- Mapear melhor o planejamento para a release 2
- Adicionar pelo menos uma funcionalidade de linkagem para a release 1 para apresentar viabilidade do projeto e concretizar MVP
